services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Prod
      args:
        - DB_PROVIDER=${DB_PROVIDER:-postgresql}
    container_name: wilayah-indonesia-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-9206}:9206"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - APP_ENV=prod  # Override nilai dari .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - wilayah-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  wilayah-network:
    driver: bridge
